'use client';

import Link from 'next/link';
import { ArrowLeft, CreditCard, FileText, Receipt, Wallet } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';

export default function BillingPage() {
  return (
    <div className="min-h-screen bg-background">
      <header className="border-b border-border"><div className="mx-auto flex h-16 max-w-6xl items-center justify-between px-4 sm:px-6 lg:px-8"><Link href="/portal/dashboard" className="inline-flex items-center gap-2 text-sm font-medium text-muted-foreground hover:text-foreground"><ArrowLeft className="h-4 w-4" /> Back to portal</Link><Link href="/" className="font-display text-lg font-bold tracking-tight">HostSuite</Link></div></header>
      <main className="mx-auto max-w-6xl px-4 py-8 sm:px-6 lg:px-8">
        <div><p className="text-sm font-medium text-primary">Billing</p><h1 className="mt-1 font-display text-3xl font-bold tracking-tight">Payments & services</h1><p className="mt-2 max-w-2xl text-sm leading-6 text-muted-foreground sm:text-base">See what you pay for, manage renewals and keep your payment history in one place.</p></div>
        <div className="mt-8 grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><Card><CardContent className="p-5"><Wallet className="h-5 w-5 text-primary" /><p className="mt-4 text-xs text-muted-foreground">Current balance</p><p className="mt-1 text-xl font-semibold">Not available yet</p></CardContent></Card><Card><CardContent className="p-5"><Receipt className="h-5 w-5 text-primary" /><p className="mt-4 text-xs text-muted-foreground">Subscriptions</p><p className="mt-1 text-xl font-semibold">Not configured</p></CardContent></Card><Card><CardContent className="p-5"><CreditCard className="h-5 w-5 text-primary" /><p className="mt-4 text-xs text-muted-foreground">Payment method</p><p className="mt-1 text-xl font-semibold">Not connected</p></CardContent></Card><Card><CardContent className="p-5"><FileText className="h-5 w-5 text-primary" /><p className="mt-4 text-xs text-muted-foreground">Invoices</p><p className="mt-1 text-xl font-semibold">No invoices yet</p></CardContent></Card></div>
        <Card className="mt-6"><CardHeader><CardTitle>Billing foundation</CardTitle><CardDescription>Payment processing will be connected after the payment provider and webhook contract are configured.</CardDescription></CardHeader><CardContent><div className="grid gap-3 md:grid-cols-2"><div className="rounded-xl border border-border p-4"><p className="font-medium">Recurring services</p><p className="mt-1 text-sm leading-6 text-muted-foreground">Hosting, business email, monitoring and other eligible services can become monthly or yearly subscriptions.</p></div><div className="rounded-xl border border-border p-4"><p className="font-medium">One-time purchases</p><p className="mt-1 text-sm leading-6 text-muted-foreground">Domains, website work and other one-time services can be tracked separately from subscriptions.</p></div><div className="rounded-xl border border-border p-4"><p className="font-medium">Renewals</p><p className="mt-1 text-sm leading-6 text-muted-foreground">The billing model supports renewal dates and auto-renew state without claiming that automatic charging is active yet.</p></div><div className="rounded-xl border border-border p-4"><p className="font-medium">Payment history</p><p className="mt-1 text-sm leading-6 text-muted-foreground">Provider webhook events should be the source of truth for successful payments, failures and refunds.</p></div></div><div className="mt-6 rounded-xl border border-primary/20 bg-primary/5 p-4 text-sm leading-6"><strong>No payment has been charged.</strong> This milestone creates the customer billing experience and data contract. Paystack/Flutterwave checkout, verified webhooks, subscription charging and service suspension/recovery require the production payment integration.</div><Button asChild variant="outline" className="mt-5"><Link href="/portal/dashboard">Return to dashboard</Link></Button></CardContent></Card>
      </main>
    </div>
  );
}
