'use client';

import Link from 'next/link';
import { ArrowLeft, ArrowRight, LifeBuoy, Mail } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';

export default function EmailServicePage() {
  return <div className="min-h-screen bg-background"><header className="border-b border-border"><div className="mx-auto flex h-16 max-w-6xl items-center justify-between px-4 sm:px-6 lg:px-8"><Link href="/portal/services" className="inline-flex items-center gap-2 text-sm font-medium text-muted-foreground hover:text-foreground"><ArrowLeft className="h-4 w-4" /> Services</Link><Link href="/" className="font-display text-lg font-bold">HostSuite</Link></div></header><main className="mx-auto max-w-5xl px-4 py-10 sm:px-6 lg:px-8"><div className="max-w-2xl"><p className="text-sm font-medium text-primary">Business email</p><h1 className="mt-2 font-display text-3xl font-bold tracking-tight">Set up professional email</h1><p className="mt-3 text-sm leading-6 text-muted-foreground">Choose this service when you want mailboxes such as hello@yourbusiness.com. HostSuite will connect mailbox provisioning and DNS through the configured provider rather than pretending an account exists.</p></div><div className="mt-8 grid gap-5 md:grid-cols-2"><Card><CardHeader><div className="flex h-11 w-11 items-center justify-center rounded-xl bg-primary/10 text-primary"><Mail className="h-5 w-5" /></div><CardTitle className="mt-3">I need business email</CardTitle></CardHeader><CardContent><p className="text-sm leading-6 text-muted-foreground">If you already have a domain, tell us which domain should be used. If not, HostSuite can help you get one first.</p><Button asChild className="mt-5 gap-2"><Link href="/portal/support">Start email setup <ArrowRight className="h-4 w-4" /></Link></Button></CardContent></Card><Card><CardHeader><CardTitle>I already have email</CardTitle></CardHeader><CardContent><p className="text-sm leading-6 text-muted-foreground">Open the existing email workspace to manage whatever mailbox data is already connected to your account.</p><Button asChild variant="outline" className="mt-5"><Link href="/portal/email">Manage email</Link></Button></CardContent></Card></div><Card className="mt-6 border-primary/20 bg-primary/5"><CardContent className="flex gap-3 p-5"><LifeBuoy className="mt-0.5 h-5 w-5 shrink-0 text-primary" /><p className="text-sm leading-6 text-muted-foreground">Mailbox credentials, DNS changes and provisioning will only be displayed after a real provider confirms the resource.</p></CardContent></Card></main></div>;
}
