'use client';

import Link from 'next/link';
import { ArrowLeft, ArrowRight, Globe, LifeBuoy } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';

export default function DomainServicePage() {
  return <div className="min-h-screen bg-background"><header className="border-b border-border"><div className="mx-auto flex h-16 max-w-6xl items-center justify-between px-4 sm:px-6 lg:px-8"><Link href="/portal/services" className="inline-flex items-center gap-2 text-sm font-medium text-muted-foreground hover:text-foreground"><ArrowLeft className="h-4 w-4" /> Services</Link><Link href="/" className="font-display text-lg font-bold">HostSuite</Link></div></header><main className="mx-auto max-w-5xl px-4 py-10 sm:px-6 lg:px-8"><div className="max-w-2xl"><p className="text-sm font-medium text-primary">Domain</p><h1 className="mt-2 font-display text-3xl font-bold tracking-tight">Get or connect a domain</h1><p className="mt-3 text-sm leading-6 text-muted-foreground">Start a domain request from your client workspace. Provider registration, renewal and DNS changes will be executed only through the configured domain provider adapter.</p></div><div className="mt-8 grid gap-5 md:grid-cols-2"><Card><CardHeader><div className="flex h-11 w-11 items-center justify-center rounded-xl bg-primary/10 text-primary"><Globe className="h-5 w-5" /></div><CardTitle className="mt-3">New domain</CardTitle></CardHeader><CardContent><p className="text-sm leading-6 text-muted-foreground">Search and register a domain once the provider-backed domain purchase flow is enabled.</p><Button asChild className="mt-5 gap-2"><Link href="/portal/support">Start a domain request <ArrowRight className="h-4 w-4" /></Link></Button></CardContent></Card><Card><CardHeader><CardTitle>Existing domain</CardTitle></CardHeader><CardContent><p className="text-sm leading-6 text-muted-foreground">View domains already connected to your account and continue with supported management actions.</p><Button asChild variant="outline" className="mt-5"><Link href="/portal/domains">Manage domains</Link></Button></CardContent></Card></div><Card className="mt-6 border-primary/20 bg-primary/5"><CardContent className="flex gap-3 p-5"><LifeBuoy className="mt-0.5 h-5 w-5 shrink-0 text-primary" /><p className="text-sm leading-6 text-muted-foreground">Need a domain urgently or want us to handle the technical details? Use Support and a person can take the request from there.</p></CardContent></Card></main></div>;
}
