import Link from 'next/link';
import { ArrowRight, CheckCircle2, LifeBuoy, Mail, Server, ShieldCheck, Sparkles, Globe2, Wrench } from 'lucide-react';
import { createServerSupabaseClient } from '@/lib/supabase-server';

const fallback = { branding: { siteName: 'HostSuite', logoUrl: '' }, hero: { headline: 'Your business deserves a digital home that is easy to manage.', subheadline: 'Domains, websites, hosting, business email and technical support — with HostSuite handling the complexity behind the scenes.', primaryCta: 'Get started', secondaryCta: 'I need help' }, pricing: { starter_ops_monthly: 5000, managed_growth_monthly: 12000 } };

export default async function Home() {
  const supabase = await createServerSupabaseClient();
  const [{ data: rows }, { data: posts }] = await Promise.all([
    supabase.from('site_settings').select('key,value').in('key', ['branding', 'hero', 'pricing']),
    supabase.from('blogs').select('id,title,slug,excerpt,published_at').eq('published', true).order('published_at', { ascending: false }).limit(3),
  ]);
  const settings = Object.fromEntries((rows ?? []).map((row) => [row.key, row.value])) as Record<string, any>;
  const branding = { ...fallback.branding, ...(settings.branding ?? {}) };
  const hero = { ...fallback.hero, ...(settings.hero ?? {}) };
  const pricing = { ...fallback.pricing, ...(settings.pricing ?? {}) };

  return <main className="min-h-screen bg-background text-foreground">
    <nav className="border-b border-border/70"><div className="mx-auto flex h-16 max-w-7xl items-center justify-between px-4 sm:px-6 lg:px-8"><Link href="/" className="flex items-center gap-2 font-bold tracking-tight">{branding.logoUrl ? <img src={branding.logoUrl} alt={branding.siteName} className="h-8 w-auto" /> : <span className="text-xl">{branding.siteName}</span>}</Link><div className="hidden items-center gap-7 text-sm text-muted-foreground md:flex"><a href="#services">Services</a><a href="#how-it-works">How it works</a><a href="#pricing">Pricing</a><a href="#blog">Resources</a></div><div className="flex items-center gap-2"><Link href="/portal/login" className="hidden rounded-lg px-3 py-2 text-sm font-medium md:block">Sign in</Link><Link href="/onboarding" className="rounded-lg bg-foreground px-4 py-2 text-sm font-semibold text-background">Get started</Link></div></div></nav>
    <section className="relative overflow-hidden"><div className="mx-auto grid max-w-7xl gap-12 px-4 py-20 sm:px-6 lg:grid-cols-[1.05fr_.95fr] lg:px-8 lg:py-28"><div className="flex flex-col justify-center"><div className="inline-flex w-fit items-center gap-2 rounded-full border border-border bg-muted/40 px-3 py-1.5 text-xs font-medium"><Sparkles className="h-3.5 w-3.5" /> Digital infrastructure for growing businesses</div><h1 className="mt-6 max-w-3xl text-5xl font-bold leading-[1.04] tracking-tight sm:text-6xl">{hero.headline}</h1><p className="mt-6 max-w-2xl text-lg leading-8 text-muted-foreground">{hero.subheadline}</p><div className="mt-8 flex flex-col gap-3 sm:flex-row"><Link href="/onboarding" className="inline-flex items-center justify-center gap-2 rounded-xl bg-foreground px-5 py-3.5 text-sm font-semibold text-background">{hero.primaryCta}<ArrowRight className="h-4 w-4" /></Link><Link href="/support" className="inline-flex items-center justify-center gap-2 rounded-xl border border-border px-5 py-3.5 text-sm font-semibold">{hero.secondaryCta}<LifeBuoy className="h-4 w-4" /></Link></div><div className="mt-7 flex flex-wrap gap-x-5 gap-y-2 text-sm text-muted-foreground"><span><CheckCircle2 className="mr-1 inline h-4 w-4" />Self-service</span><span><CheckCircle2 className="mr-1 inline h-4 w-4" />Managed support</span><span><CheckCircle2 className="mr-1 inline h-4 w-4" />Emergency desk</span></div></div><div className="rounded-3xl border border-border bg-muted/30 p-5 shadow-sm sm:p-7"><div className="rounded-2xl border border-border bg-background p-5 sm:p-6"><div className="flex items-center justify-between"><div><p className="text-xs text-muted-foreground">Business infrastructure</p><p className="mt-1 font-semibold">Everything is healthy</p></div><span className="rounded-full bg-muted px-2.5 py-1 text-xs">Live</span></div><div className="mt-6 grid gap-3 sm:grid-cols-2"><Status icon={<Globe2 className="h-4 w-4" />} label="Domain" /><Status icon={<Server className="h-4 w-4" />} label="Hosting" /><Status icon={<Mail className="h-4 w-4" />} label="Business email" /><Status icon={<ShieldCheck className="h-4 w-4" />} label="SSL & security" /></div><div className="mt-5 rounded-xl bg-muted/60 p-4"><p className="text-sm font-medium">Something went wrong?</p><p className="mt-1 text-xs leading-5 text-muted-foreground">HostSuite can check what happened, guide you through a fix or escalate it to our technical desk.</p></div></div></div></div></section>
    <section id="services" className="border-y border-border bg-muted/20"><div className="mx-auto max-w-7xl px-4 py-20 sm:px-6 lg:px-8"><div className="max-w-2xl"><p className="text-sm font-semibold">One roof. Less technical stress.</p><h2 className="mt-2 text-3xl font-bold tracking-tight sm:text-4xl">Use the tools yourself. Or let us handle them.</h2><p className="mt-4 text-muted-foreground">HostSuite is designed around the way real businesses work — sometimes you want control, sometimes you just want the problem gone.</p></div><div className="mt-10 grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><Service icon={<Globe2 />} title="Domains" text="Register, connect, renew and manage your business domain." /><Service icon={<Server />} title="Hosting" text="Reliable hosting with a simple customer experience." /><Service icon={<Mail />} title="Business email" text="Get professional email on your own domain and keep it healthy." /><Service icon={<Wrench />} title="Technical desk" text="Support, monitoring and emergency technical help when you need it." /></div></div></section>
    <section id="how-it-works"><div className="mx-auto max-w-7xl px-4 py-20 sm:px-6 lg:px-8"><div className="grid gap-12 lg:grid-cols-2"><div><p className="text-sm font-semibold">Simple by design</p><h2 className="mt-2 text-3xl font-bold tracking-tight sm:text-4xl">Tell us what you need. We figure out the technical path.</h2><p className="mt-4 leading-7 text-muted-foreground">You don't need to know whether your problem is DNS, SSL, hosting or email configuration. HostSuite turns technical infrastructure into straightforward tasks.</p></div><div className="space-y-4"><Step n="01" title="Choose what you need" text="Website, domain, hosting, email or technical help." /><Step n="02" title="Do it yourself or hand it over" text="Use the self-service tools or ask HostSuite to manage it for you." /><Step n="03" title="Stay informed" text="See service health, billing, renewals and support from one place." /></div></div></div></section>
    <section id="pricing" className="border-y border-border bg-muted/20"><div className="mx-auto max-w-7xl px-4 py-20 sm:px-6 lg:px-8"><div className="max-w-2xl"><p className="text-sm font-semibold">Pricing</p><h2 className="mt-2 text-3xl font-bold tracking-tight">Start small. Upgrade when you need more help.</h2></div><div className="mt-10 grid gap-5 lg:grid-cols-2"><Plan name="Starter Ops" price={pricing.starter_ops_monthly} text="For businesses that want a simple digital infrastructure home." features={['Core hosting operations','Basic monitoring','Customer portal','Technical support']} /><Plan name="Managed Growth" price={pricing.managed_growth_monthly} text="For businesses that want HostSuite to take more responsibility." features={['Everything in Starter Ops','Managed website operations','Priority support','Proactive monitoring']} /></div></div></section>
    <section id="blog"><div className="mx-auto max-w-7xl px-4 py-20 sm:px-6 lg:px-8"><div className="flex items-end justify-between gap-4"><div><p className="text-sm font-semibold">Resources</p><h2 className="mt-2 text-3xl font-bold tracking-tight">Practical guides for running online</h2></div><Link href="/blog" className="hidden text-sm font-semibold sm:block">View all</Link></div><div className="mt-8 grid gap-5 md:grid-cols-3">{(posts ?? []).map((post) => <article key={post.id} className="rounded-2xl border border-border p-5"><p className="text-xs text-muted-foreground">{post.published_at ? new Date(post.published_at).toLocaleDateString() : 'HostSuite'}</p><h3 className="mt-3 text-lg font-semibold">{post.title}</h3><p className="mt-2 text-sm leading-6 text-muted-foreground">{post.excerpt}</p><Link href={`/blog/${post.slug}`} className="mt-5 inline-flex items-center gap-1 text-sm font-semibold">Read article <ArrowRight className="h-3.5 w-3.5" /></Link></article>)}{(!posts || posts.length === 0) && <div className="rounded-2xl border border-dashed border-border p-8 text-sm text-muted-foreground md:col-span-3">Your published guides will appear here. Publish them from the HostSuite CMS.</div>}</div></div></section>
    <footer className="border-t border-border"><div className="mx-auto flex max-w-7xl flex-col gap-4 px-4 py-8 text-sm text-muted-foreground sm:flex-row sm:items-center sm:justify-between sm:px-6 lg:px-8"><span>© {new Date().getFullYear()} {branding.siteName}. Digital infrastructure without the technical headache.</span><div className="flex gap-4"><Link href="/support">Support</Link><Link href="/portal/login">Customer portal</Link></div></div></footer>
  </main>;
}

function Status({ icon, label }: { icon: React.ReactNode; label: string }) { return <div className="flex items-center gap-3 rounded-xl border border-border p-3"><span className="rounded-lg bg-muted p-2">{icon}</span><div><p className="text-sm font-medium">{label}</p><p className="text-xs text-muted-foreground">Healthy</p></div></div>; }
function Service({ icon, title, text }: { icon: React.ReactNode; title: string; text: string }) { return <div className="rounded-2xl border border-border bg-background p-5"><span className="inline-flex rounded-lg bg-muted p-2">{icon}</span><h3 className="mt-4 font-semibold">{title}</h3><p className="mt-2 text-sm leading-6 text-muted-foreground">{text}</p></div>; }
function Step({ n, title, text }: { n: string; title: string; text: string }) { return <div className="flex gap-4 rounded-2xl border border-border p-5"><span className="text-xs font-semibold text-muted-foreground">{n}</span><div><h3 className="font-semibold">{title}</h3><p className="mt-1 text-sm leading-6 text-muted-foreground">{text}</p></div></div>; }
function Plan({ name, price, text, features }: { name: string; price: number; text: string; features: string[] }) { return <div className="rounded-2xl border border-border bg-background p-6"><p className="font-semibold">{name}</p><p className="mt-2 text-sm text-muted-foreground">{text}</p><p className="mt-6 text-3xl font-bold">₦{Number(price).toLocaleString()}<span className="text-sm font-normal text-muted-foreground"> / month</span></p><ul className="mt-6 space-y-3">{features.map((feature) => <li key={feature} className="flex gap-2 text-sm"><CheckCircle2 className="mt-0.5 h-4 w-4 shrink-0" />{feature}</li>)}</ul><Link href="/onboarding" className="mt-7 inline-flex w-full items-center justify-center rounded-xl bg-foreground px-4 py-3 text-sm font-semibold text-background">Choose {name}</Link></div>; }
