'use client';

import { useEffect, useState } from 'react';
import Link from 'next/link';
import { AlertTriangle, ArrowRight, Globe2, Loader2, Plus, RefreshCw, Sparkles } from 'lucide-react';
import { useRouter } from 'next/navigation';
import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { supabase, useAuth } from '@/lib/supabase-client';

type Project = { id: string; name: string; status: string; provider: string | null; deployment_url: string | null; custom_domain: string | null; metadata: Record<string, unknown> | null; updated_at: string };
type Website = { id: string; service_name: string; status: string; configuration: Record<string, unknown> | null; provider: string | null; provider_status: string | null; created_at: string };
function text(value: unknown, fallback = 'Not connected') { return typeof value === 'string' && value.trim() ? value : fallback; }
function statusClass(status: string) { return status === 'active' || status === 'deployed' || status === 'ready' ? 'border-emerald-500/20 bg-emerald-500/5 text-emerald-700 dark:text-emerald-400' : status === 'failed' ? 'border-destructive/20 bg-destructive/5 text-destructive' : 'border-amber-500/20 bg-amber-500/5 text-amber-700 dark:text-amber-400'; }
export default function WebsitesPage() {
  const { user, loading } = useAuth(); const router = useRouter();
  const [projects, setProjects] = useState<Project[]>([]); const [websites, setWebsites] = useState<Website[]>([]); const [error, setError] = useState(false); const [refreshing, setRefreshing] = useState(false);
  async function load() { if (!user) return; setRefreshing(true); try { const [{ data, error: websiteError }, projectResponse] = await Promise.all([supabase.from('service_instances').select('id,service_name,status,configuration,provider,provider_status,created_at').eq('user_id', user.id).eq('service_type', 'website').order('created_at', { ascending: false }), fetch('/api/ai-builder/projects')]); if (websiteError) throw websiteError; if (!projectResponse.ok) throw new Error('projects'); const result = await projectResponse.json() as { projects?: Project[] }; setWebsites((data as Website[]) ?? []); setProjects(result.projects ?? []); setError(false); } catch { setError(true); } finally { setRefreshing(false); } }
  useEffect(() => { if (!loading && !user) router.replace('/portal'); if (user) void load(); }, [loading, user, router]);
  if (loading || !user) return <div className="flex min-h-screen items-center justify-center"><Loader2 className="h-8 w-8 animate-spin text-primary" /></div>;
  return <main className="min-h-screen bg-background px-4 py-8 sm:px-6 lg:px-8"><div className="mx-auto max-w-6xl">
    <div className="flex flex-col gap-5 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-sm font-medium text-primary">Websites</p><h1 className="mt-1 font-display text-3xl font-bold tracking-tight sm:text-4xl">Your website workspace</h1><p className="mt-2 max-w-2xl text-muted-foreground">Manage websites actually connected to your HostSuite account, or start a new one with the AI builder.</p></div><div className="flex gap-2"><Button variant="outline" onClick={() => void load()} disabled={refreshing}><RefreshCw className={`mr-2 h-4 w-4 ${refreshing ? 'animate-spin' : ''}`} /> Refresh</Button><Button asChild><Link href="/portal/ai-builder"><Sparkles className="mr-2 h-4 w-4" /> Build with AI</Link></Button></div></div>
    {error && <div className="mt-6 flex gap-3 rounded-2xl border border-amber-500/30 bg-amber-500/5 p-4 text-sm"><AlertTriangle className="mt-0.5 h-5 w-5 shrink-0 text-amber-600" /><div><p className="font-semibold">We’re having trouble loading your websites.</p><p className="mt-1 text-muted-foreground">This is a temporary problem on our side. Your account and websites have not been changed. Please try again shortly.</p></div></div>}
    {!error && <><section className="mt-7 grid gap-3 sm:grid-cols-3"><Summary label="Connected websites" value={websites.length.toString()} /><Summary label="AI projects" value={projects.length.toString()} /><Summary label="Published" value={projects.filter((p) => p.status === 'deployed').length.toString()} /></section>
    <section className="mt-7 grid gap-4 lg:grid-cols-2">{websites.map((site) => { const config = site.configuration ?? {}; return <Card key={site.id}><CardContent className="p-5"><div className="flex gap-4"><div className="flex h-11 w-11 shrink-0 items-center justify-center rounded-xl bg-primary/10 text-primary"><Globe2 className="h-5 w-5" /></div><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><h2 className="font-semibold">{site.service_name}</h2><Badge variant="outline" className={`capitalize ${statusClass(site.status)}`}>{site.status.replaceAll('_', ' ')}</Badge></div><p className="mt-2 text-sm text-muted-foreground">Domain: <strong className="text-foreground">{text(config.domain)}</strong></p><p className="text-sm text-muted-foreground">Provider: <strong className="text-foreground">{text(site.provider, 'Not configured')}</strong></p><div className="mt-4"><Button asChild variant="outline"><Link href={`/portal/services/${site.id}`}>Manage website <ArrowRight className="ml-2 h-4 w-4" /></Link></Button></div></div></div></CardContent></Card>; })}
      {projects.map((project) => <Card key={project.id}><CardContent className="p-5"><div className="flex gap-4"><div className="flex h-11 w-11 shrink-0 items-center justify-center rounded-xl bg-primary/10 text-primary"><Sparkles className="h-5 w-5" /></div><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><h2 className="truncate font-semibold">{project.name}</h2><Badge variant="outline" className={`capitalize ${statusClass(project.status)}`}>{project.status}</Badge></div><p className="mt-2 text-sm text-muted-foreground">Domain: <strong className="text-foreground">{text(project.custom_domain)}</strong></p><p className="text-sm text-muted-foreground">Deployment: <strong className="text-foreground">{project.deployment_url ? 'Published' : 'Not deployed'}</strong></p><div className="mt-4"><Button asChild variant="outline"><Link href={`/portal/ai-builder/${project.id}`}>Open project <ArrowRight className="ml-2 h-4 w-4" /></Link></Button></div></div></div></CardContent></Card>)}
    </section>{websites.length === 0 && projects.length === 0 && <Card className="mt-7 border-dashed"><CardHeader><div className="flex h-12 w-12 items-center justify-center rounded-2xl bg-primary/10 text-primary"><Globe2 className="h-6 w-6" /></div><CardTitle className="mt-2">No website yet</CardTitle><CardDescription>Start a website with HostSuite AI, or connect a website service after it is actually purchased or provisioned.</CardDescription></CardHeader><CardContent><Button asChild><Link href="/portal/ai-builder"><Plus className="mr-2 h-4 w-4" /> Start a website</Link></Button></CardContent></Card>}</>}
  </div></main>;
}
function Summary({ label, value }: { label: string; value: string }) { return <div className="rounded-2xl border bg-card p-4"><p className="text-xs text-muted-foreground">{label}</p><p className="mt-1 text-2xl font-bold">{value}</p></div>; }
